"""
What the shipped `SHA256SUMS` manifests cover, and what they deliberately do not.

`cd study/artifacts && sha256sum -c SHA256SUMS` is the first command README.md
and docs/VERIFY.md ask a reader to run, so a manifest that fails on a correct
clone costs more than one that covers less. Renders are that case: a dry run on
another machine found all six `signals/signals_pareto_*.png` 10-13% different
pixel for pixel and `figures/extreme_stopping.png` about 7.5%, while every CSV
view they are drawn from - `tables/stopping/stopping_extreme.csv` among them -
regenerated byte for byte. The pictures were the only failures, and they were
failures of matplotlib and the font set, not of the study.

So the manifests checksum the data and leave the pictures out, and these tests
pin that in both directions: out of the manifest, and out of ``--check``'s
unlisted-files report, which would otherwise turn the exclusion straight back
into the failure it was meant to remove. They also pin that the exclusion is
narrow - every file that is not a render is still covered - so "leave the
pictures out" cannot quietly become "leave things out".
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
TOOLS = str(REPO / "tools")
MANIFESTS = (REPO / "study" / "artifacts", REPO / "study" / "jobs")


@pytest.fixture()
def checksums():
    if TOOLS not in sys.path:
        sys.path.insert(0, TOOLS)
    import artifact_checksums

    return artifact_checksums


@pytest.mark.parametrize("root", MANIFESTS, ids=lambda p: p.name)
def test_no_shipped_manifest_lists_a_rendered_image(root, checksums):
    """
    The claim docs/VERIFY.md makes to the reader, asserted on the shipped file.

    A regenerated manifest is the likeliest way this comes back: someone runs
    the tool on a tree, the tool has forgotten the rule, and the next reviewer
    on a different matplotlib gets seven FAILED lines for pictures that are fine.
    """
    listed = checksums.parse((root / checksums.MANIFEST).read_text())
    renders = sorted(n for n in listed if Path(n).suffix.lower() in checksums.RENDERED)
    assert not renders, (
        f"{root.name}/SHA256SUMS hashes {len(renders)} rendered image(s), whose "
        f"bytes are a property of the renderer: {renders[:5]}"
    )


@pytest.mark.parametrize("root", MANIFESTS, ids=lambda p: p.name)
def test_every_file_that_is_not_a_render_is_in_the_manifest(root, checksums):
    """
    The other half: the exclusion covers pictures and nothing else.

    Compared on names rather than on hashes - ``sha256sum -c`` already proves the
    hashes, and this is the failure it cannot see, a shipped artefact that no
    manifest covers and that therefore verifies by saying nothing about itself.
    """
    listed = set(checksums.parse((root / checksums.MANIFEST).read_text()))
    on_disk = {
        path.relative_to(root).as_posix()
        for path in root.rglob("*")
        if path.is_file()
        and path.name != checksums.MANIFEST
        and not checksums.is_render(path)
    }
    assert on_disk - listed == set(), "shipped and in no manifest"
    assert listed - on_disk == set(), "in the manifest and not shipped"


def test_the_excluded_renders_are_really_there(checksums):
    """
    Guard against the two tests above passing because the tree holds no picture
    at all, which would make the whole exclusion untested and look green.
    """
    renders = [
        path for path in (REPO / "study" / "artifacts").rglob("*")
        if path.is_file() and checksums.is_render(path)
    ]
    assert len(renders) >= 7, (
        "study/artifacts is expected to ship the six Pareto plots and "
        f"extreme_stopping.png at least; found {len(renders)} render(s)"
    )


def test_the_checker_skips_renders_when_it_writes_and_when_it_checks(
    checksums, tmp_path, capsys
):
    """
    The round trip, on a tree small enough to reason about.

    ``--check`` reporting an unlisted file is the behaviour that makes the
    manifest trustworthy; it is also what would fail on every render if the
    exclusion lived only in the writing half. A picture added after the manifest
    was written must therefore be as invisible as one that was there all along.
    """
    (tmp_path / "view.csv").write_text("a,b\n1,2\n")
    (tmp_path / "plot.png").write_bytes(b"\x89PNG not really")

    entries = checksums.catalogue(tmp_path)
    assert list(entries) == ["view.csv"]

    (tmp_path / checksums.MANIFEST).write_text(checksums.render(entries))
    assert checksums.check(tmp_path, checksums.catalogue(tmp_path)) == 0

    (tmp_path / "figure.pdf").write_bytes(b"%PDF-1.4 not really")
    assert checksums.check(tmp_path, checksums.catalogue(tmp_path)) == 0

    (tmp_path / "late.csv").write_text("c\n3\n")
    assert checksums.check(tmp_path, checksums.catalogue(tmp_path)) == 1
    assert "no manifest" in capsys.readouterr().err
