#!/usr/bin/env python3
"""Emit the appendix weight-sensitivity tabulars from
weight_sensitivity_*.csv.

Same contract as make_paper_tables.py: values verbatim from the CSVs, no hand
numbers, and no run-record identifier on the page.  Each row already names its
method, so the cells print the winning *setting* alone --- ``$\\lambda{=}8$``
rather than a grid key --- which is how the field tabulates a sweep.  A method
with no free parameter prints its short name instead.  Rerun after any data
refresh.

The two tabulars are bare on purpose: the float, the caption and the label
belong to the appendix that places them.

Views are read through make_paper_tables' own resolver, so this reads the
manuscript's ``data/`` when run from a paper checkout and
``study/artifacts/Digits_study01/tables/`` when run from the repository;
``FOA_PAPER_DATA`` overrides both.  The tabulars are written to ``tables/``
under ``FOA_PAPER_OUT``, the same variable every other generator here takes.
"""

import argparse
import csv
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from make_paper_tables import locate, out_dir  # noqa: E402
from paper_names import family_label, params, short  # noqa: E402


def render(grid: str) -> tuple[str, int, int]:
    """The tabular for one grid, plus its row and identifier counts."""
    src = locate(f"weight_sensitivity_{grid}.csv")
    with open(src) as fh:
        rows = list(csv.DictReader(fh))
    # Name the view by the directory it actually came from: ``data/`` in a
    # manuscript checkout, ``tables/`` in the repository.  A fixed prefix would
    # be wrong in one of the two.
    origin = os.path.join(os.path.basename(os.path.dirname(src)),
                          os.path.basename(src))
    cols = [c for c in rows[0] if c.startswith("w=")]
    lines = [
        "% GENERATED by make_sensitivity_tables.py from "
        f"{origin} -- do not edit",
        "% each row names its method; the cells are the winning setting at "
        "that price of forgetting",
        "\\begin{tabular}{@{}l" + "l" * len(cols) + "c@{}}",
        "\\toprule",
        "Method & " + " & ".join(f"${c}$" for c in cols) + " & moves \\\\",
        "\\midrule",
    ]
    ids = set()
    for r in rows:
        cells = []
        for c in cols:
            ids.add(r[c])
            cells.append(params(r[c]) if "_" in r[c] else short(r[c]))
        moved = "$\\bullet$" if r["changed"] == "1" else ""
        lines.append(family_label(r["method"]) + " & " + " & ".join(cells)
                     + f" & {moved} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    text = "\n".join(lines) + "\n"

    # the contract: no run-record identifier survives into the page
    for ident in sorted(i for i in ids if "_" in i):
        for spelling in (ident, ident.replace("_", "\\_")):
            assert spelling not in text, (
                f"sensitivity_{grid}.tex prints the identifier {ident!r}; "
                "name it in paper_names.py instead")
    assert not re.search(r"\\code\{", text), f"sensitivity_{grid}.tex sets code"
    return text, len(rows), len(ids)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="do not write; fail if a tabular is out of date")
    args = ap.parse_args()

    out = os.path.join(out_dir(), "tables")
    if not args.check:
        os.makedirs(out, exist_ok=True)

    stale = []
    for grid in ("agg", "reg"):
        text, nrows, nids = render(grid)
        path = os.path.join(out, f"sensitivity_{grid}.tex")
        if args.check:
            current = open(path).read() if os.path.isfile(path) else None
            if current != text:
                stale.append(path)
        else:
            with open(path, "w") as fh:
                fh.write(text)
        print(f"sensitivity_{grid}.tex: {nrows} rows, {nids} identifiers named")

    if stale:
        sys.exit("out of date, rerun without --check:\n  "
                 + "\n  ".join(stale))
    return 0


if __name__ == "__main__":
    sys.exit(main())
