#!/usr/bin/env python3
"""
What this study actually ran, read off the study root.

A run book says how the study is meant to go. This says how it went: which
stages exist, how many tasks each holds, how many result folders each produced,
which selections were made and what they chose. It is generated rather than
written, because a hand-kept record drifts from the runs the moment a stage is
re-run, and a record that disagrees with the disk is worse than none.

    python tools/study_record.py --root "$FOA_STUDY_DIR" > docs/STUDY_RECORD.md

Nothing here trains, selects, or writes into the study.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

#: Which result folders a stage's tasks land in, by the prefix they carry.
#:
#: These are the stages of the CURRENT programme. The map used to name
#: s04-s07, the screens and finals of the prior one, which now live in
#: jobs/superseded/ - so the record it generated listed stages nobody may
#: re-run and left every live stage's folder count blank. A blank column reads
#: as "this stage produced nothing", which is the opposite of what it meant.
#:
#: A stage may need more than one prefix, and the blends are why. All three
#: regularisation-final stages write under d01_regfull_: s17 writes the seven
#: penalties per schedule, s18 writes hybrid_mix* and s19 hybrid_seq_mix*. A
#: bare "d01_regfull_" credits s17 with all hundred folders when seventy are
#: its own, and "d01_regfull_hybrid_" credits s18 with s19's fifteen as well.
#: So s17 is named by the two schedule prefixes it actually wrote, and each
#: blend by its own full stem. The folder count is a check on the task count
#: beside it, and a count that silently absorbs another stage's folders cannot
#: perform that check.
PREFIXES = {
    "s09_agg_screen2": ("d01_agg_",),
    "s10_agg_full2": ("d01_aggfull_",),
    "s16_reg_screen3": ("d01_reg_",),
    "s17_reg_full4": ("d01_regfull_concurrent_", "d01_regfull_sequential_"),
    "s18_hybrid": ("d01_regfull_hybrid_mix",),
    "s19_hybrid_seq": ("d01_regfull_hybrid_seq_mix",),
    "s20_combos4": ("d01_combo_",),
    "d01_five": ("d01_five_",),
    "d01_c10d10": ("d01_c10d10_",),
    "d01_c20": ("d01_c20d",),
    "d01_extreme": ("d01_extreme_",),
}

#: The carry settings and the repair, in the order they ran. Their names sort
#: before every s* stage that builds their inputs, so the order is stated
#: rather than inferred - the same reason tools/check_programme.py declares it.
CARRY = ("d01_c5_references.txt", "d01_c20_references.txt", "d01_five.txt",
         "d01_c20.txt", "d01_extreme.txt", "d01_c10d10.txt",
         "d01_size_evals_rerun.txt")


def runnable(path: Path) -> int:
    return sum(1 for line in path.read_text().splitlines()
               if line.strip() and not line.strip().startswith("#"))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", required=True, type=Path)
    args = ap.parse_args()
    root = args.root

    print(f"# Study record: {root.name}\n")
    print("Generated by `tools/study_record.py` from the study root. Every figure "
          "below is read off disk, not remembered.\n")

    # ------------------------------------------------------------- inputs
    print("## Inputs\n")
    counts = root / "outliers" / "writer_counts.json"
    if counts.is_file():
        c = json.loads(counts.read_text())
        print(f"- corpus: **{c['writers']} writers**, {c['rows']:,} rows, "
              f"{c['num_classes']} classes")
    for name, label in (("g0_selection.json", "shipped model g-0"),):
        path = root / name
        if path.is_file():
            s = json.loads(path.read_text())
            print(f"- {label}: fold **{s['selected_fold']}** of "
                  f"{len(s.get('folds', []))}, validation {s['val_mean']:.4f}, "
                  f"test {s['test_mean']:.4f}")
    for size in (5, 10, 20):
        path = root / "outliers" / f"cohort_worst{size}.json"
        if path.is_file():
            payload = json.loads(path.read_text())
            clients = payload["clients"] if isinstance(payload, dict) else payload
            print(f"- cohort worst-{size}: {len(clients)} clients")

    # -------------------------------------------------------------- stages
    print("\n## Stages\n")
    print("| stage | tasks | result folders |")
    print("|---|---|---|")
    stages = sorted((root / "jobs").glob("s*.txt"))
    stages += [root / "jobs" / name for name in CARRY
               if (root / "jobs" / name).is_file()]
    for path in stages:
        stem = path.stem
        n = runnable(path)
        prefixes = PREFIXES.get(stem)
        made = (sum(len(list(root.glob(f"{prefix}*"))) for prefix in prefixes)
                if prefixes else "")
        print(f"| `{stem}` | {n} | {made} |")

    walked = {p.name for p in stages}
    other = sorted(p for p in (root / "jobs").glob("*.txt") if p.name not in walked)
    if other:
        print("\nAlso in `jobs/`, outside the programme order: "
              + ", ".join(f"`{p.stem}`" for p in other)
              + ". Superseded files live in `jobs/superseded/` and are not "
                "listed here at all.")

    # ----------------------------------------------------------- selections
    print("\n## Selections\n")
    for name, label in (("p11_agg_method_winners.json", "Aggregation"),
                        ("p13_reg_method_winners.json", "Regularisation")):
        path = root / "tables" / name
        if not path.is_file():
            continue
        record = json.loads(path.read_text())
        measured = sum(1 for v in record.values() if v.get("measured"))
        print(f"### {label}: {len(record)} winners ({measured} measured)\n")
        print("| method | winning cell | adaptation | preservation |")
        print("|---|---|---|---|")
        for key, v in sorted(record.items(),
                             key=lambda kv: -(kv[1].get("adaptation") or 0)):
            if not v.get("measured"):
                print(f"| {key} | `{v.get('winner')}` | not measured | |")
                continue
            print(f"| {key} | `{v['winner']}` | {v['adaptation']:.4f} | "
                  f"{v['preservation']:.4f} |")
        print()

    # ------------------------------------------------- reopened boundaries
    for grid in ("agg", "reg"):
        path = root / "tables" / f"boundary_ext_cells_{grid}.json"
        if not path.is_file():
            continue
        cells = json.loads(path.read_text())
        print(f"### Ranges reopened, {grid}: {len(cells)} cells\n")
        print("A winner at the end of a swept row is only the best of what was "
              "tried, so the row is continued in the direction it ran out. The "
              "rule can fire more than once; a strength of zero is where it stops.\n")
        for cell in cells:
            print(f"- `{cell['id']}` - {cell.get('note', '')}")
        print()

    hits = root / "tables" / "BOUNDARY_HITS.txt"
    if hits.is_file():
        remaining = [l for l in hits.read_text().splitlines() if l.strip()]
        print(f"### Winners still on an edge after the last selection: "
              f"{len(remaining)}\n")
        for line in remaining:
            print(f"- {line.split(chr(9))[-1]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
