#!/usr/bin/env python3
"""
What this study actually ran, read off the study root.

A run book says how the study is meant to go. This says how it went: which
stages exist, how many tasks each holds, how many result folders each produced,
which selections were made and what they chose. It is generated rather than
written, because a hand-kept record drifts from the runs the moment a stage is
re-run, and a record that disagrees with the disk is worse than none.

    python tools/study_record.py --root "$FOA_STUDY_DIR" > docs/STUDY_RECORD.md

Nothing here trains, selects, or writes into the study.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

#: Which result folders a stage's tasks land in, by the prefix they carry.
PREFIXES = {
    "s04_agg_screen": "d01_agg_",
    "s04b_agg_ext": "d01_agg_",
    "s04c_agg_ext2": "d01_agg_",
    "s05_agg_full": "d01_aggfull_",
    "s06_reg_screen": "d01_reg_",
    "s06b_reg_ext": "d01_reg_",
    "s06c_reg_ext2": "d01_reg_",
    "s06d_reg_ext3": "d01_reg_",
    "s07_reg_full": "d01_regfull_",
}


def runnable(path: Path) -> int:
    return sum(1 for line in path.read_text().splitlines()
               if line.strip() and not line.strip().startswith("#"))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", required=True, type=Path)
    args = ap.parse_args()
    root = args.root

    print(f"# Study record: {root.name}\n")
    print("Generated by `tools/study_record.py` from the study root. Every figure "
          "below is read off disk, not remembered.\n")

    # ------------------------------------------------------------- inputs
    print("## Inputs\n")
    counts = root / "outliers" / "writer_counts.json"
    if counts.is_file():
        c = json.loads(counts.read_text())
        print(f"- corpus: **{c['writers']} writers**, {c['rows']:,} rows, "
              f"{c['num_classes']} classes")
    for name, label in (("g0_selection.json", "shipped model g-0"),):
        path = root / name
        if path.is_file():
            s = json.loads(path.read_text())
            print(f"- {label}: fold **{s['selected_fold']}** of "
                  f"{len(s.get('folds', []))}, validation {s['val_mean']:.4f}, "
                  f"test {s['test_mean']:.4f}")
    for size in (5, 10, 20):
        path = root / "outliers" / f"cohort_worst{size}.json"
        if path.is_file():
            payload = json.loads(path.read_text())
            clients = payload["clients"] if isinstance(payload, dict) else payload
            print(f"- cohort worst-{size}: {len(clients)} clients")

    # -------------------------------------------------------------- stages
    print("\n## Stages\n")
    print("| stage | tasks | result folders |")
    print("|---|---|---|")
    for path in sorted((root / "jobs").glob("s*.txt")):
        stem = path.stem
        n = runnable(path)
        prefix = PREFIXES.get(stem)
        made = len(list(root.glob(f"{prefix}*"))) if prefix else ""
        print(f"| `{stem}` | {n} | {made} |")
    for path in sorted((root / "jobs").glob("d01_*_references.txt")):
        print(f"| `{path.stem}` | {runnable(path)} | |")

    # ----------------------------------------------------------- selections
    print("\n## Selections\n")
    for name, label in (("p11_agg_method_winners.json", "Aggregation"),
                        ("p13_reg_method_winners.json", "Regularisation")):
        path = root / "tables" / name
        if not path.is_file():
            continue
        record = json.loads(path.read_text())
        measured = sum(1 for v in record.values() if v.get("measured"))
        print(f"### {label}: {len(record)} winners ({measured} measured)\n")
        print("| method | winning cell | adaptation | preservation |")
        print("|---|---|---|---|")
        for key, v in sorted(record.items(),
                             key=lambda kv: -(kv[1].get("adaptation") or 0)):
            if not v.get("measured"):
                print(f"| {key} | `{v.get('winner')}` | not measured | |")
                continue
            print(f"| {key} | `{v['winner']}` | {v['adaptation']:.4f} | "
                  f"{v['preservation']:.4f} |")
        print()

    # ------------------------------------------------- reopened boundaries
    for grid in ("agg", "reg"):
        path = root / "tables" / f"boundary_ext_cells_{grid}.json"
        if not path.is_file():
            continue
        cells = json.loads(path.read_text())
        print(f"### Ranges reopened, {grid}: {len(cells)} cells\n")
        print("A winner at the end of a swept row is only the best of what was "
              "tried, so the row is continued in the direction it ran out. The "
              "rule can fire more than once; a strength of zero is where it stops.\n")
        for cell in cells:
            print(f"- `{cell['id']}` - {cell.get('note', '')}")
        print()

    hits = root / "tables" / "BOUNDARY_HITS.txt"
    if hits.is_file():
        remaining = [l for l in hits.read_text().splitlines() if l.strip()]
        print(f"### Winners still on an edge after the last selection: "
              f"{len(remaining)}\n")
        for line in remaining:
            print(f"- {line.split(chr(9))[-1]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
